/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Time = bigint;
export interface MemoryJarEntry {
    savedAt: Time;
    postId: string;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface StatusUpdate {
    music?: MusicAttachment;
    text?: string;
    timestamp: Time;
    image?: ExternalBlob;
}
export interface PhotoAlbumView {
    id: string;
    name: string;
    photos: Array<ExternalBlob>;
}
export interface ChallengeCompletion {
    id: string;
    user: Principal;
    challengeId: string;
    timestamp: Time;
    postId: string;
}
export interface VideoAlbumView {
    id: string;
    name: string;
    videos: Array<ExternalBlob>;
}
export interface LoveNote {
    id: string;
    recipient: Principal;
    sender: Principal;
    message: string;
    timestamp: Time;
}
export interface Post {
    id: string;
    parentPostId?: string;
    video?: ExternalBlob;
    author: Principal;
    likes: bigint;
    timestamp: Time;
    caption: string;
    category: PostCategory;
    comments: bigint;
    photo?: ExternalBlob;
    isFlagged: boolean;
}
export interface KindnessMatch {
    sharedCategories: Array<PostCategory>;
    withUser: Principal;
    compatibilityScore: bigint;
    reason: string;
}
export interface DailyChallenge {
    id: string;
    date: Time;
    category: PostCategory;
    prompt: string;
}
export interface MusicAttachment {
    id: string;
    title: string;
    audioFile: ExternalBlob;
    artist: string;
}
export interface UserProfile {
    bio: string;
    principal: Principal;
    statusImage?: ExternalBlob;
    name: string;
    layoutPreferences?: string;
    statusText?: string;
    followers: bigint;
    following: bigint;
    profilePicture?: ExternalBlob;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum PostCategory {
    other = "other",
    actsOfKindness = "actsOfKindness",
    environmental = "environmental",
    communityService = "communityService"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    addPhotoToAlbum(albumId: string, photo: ExternalBlob): Promise<boolean>;
    addStatusUpdate(text: string | null, image: ExternalBlob | null, music: MusicAttachment | null): Promise<void>;
    addToMemoryJar(postId: string): Promise<boolean>;
    addVideoToAlbum(albumId: string, video: ExternalBlob): Promise<boolean>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    attachMusicToStatus(musicId: string, title: string, artist: string, audio: ExternalBlob): Promise<void>;
    completeDailyChallenge(challengeId: string, postId: string): Promise<ChallengeCompletion>;
    createPhotoAlbum(albumId: string, albumName: string): Promise<void>;
    createPost(id: string, caption: string, parentPostId: string | null, photo: ExternalBlob | null, video: ExternalBlob | null, category: PostCategory): Promise<Post>;
    createVideoAlbum(albumId: string, albumName: string): Promise<void>;
    getAllMusicAttachments(): Promise<Array<MusicAttachment>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getChallengeCompletions(challengeId: string): Promise<Array<ChallengeCompletion>>;
    getFriendsStatusUpdates(friends: Array<Principal>): Promise<Array<StatusUpdate>>;
    getLoveNotesCount(): Promise<bigint>;
    getMusicAttachment(musicId: string): Promise<MusicAttachment | null>;
    getMyLoveNotes(): Promise<Array<LoveNote>>;
    getMyMemoryJar(): Promise<Array<MemoryJarEntry>>;
    getMyPhotoAlbums(): Promise<Array<PhotoAlbumView>>;
    getMyVideoAlbums(): Promise<Array<VideoAlbumView>>;
    getRippleChain(postId: string): Promise<Array<Post>>;
    getTodaysChallenge(): Promise<DailyChallenge | null>;
    getTopMatches(user: Principal): Promise<Array<KindnessMatch>>;
    getUserAlbums(user: Principal): Promise<{
        photoAlbums: Array<PhotoAlbumView>;
        videoAlbums: Array<VideoAlbumView>;
    }>;
    getUserChallengeCompletions(user: Principal): Promise<Array<ChallengeCompletion>>;
    getUserPhotoAlbums(user: Principal): Promise<Array<PhotoAlbumView>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getUserStatusUpdates(user: Principal): Promise<Array<StatusUpdate>>;
    getUserVideoAlbums(user: Principal): Promise<Array<VideoAlbumView>>;
    healthcheckWithPhotos(): Promise<{
        photoSystem: boolean;
    }>;
    healthcheckWithStorageCleanup(): Promise<{
        storageSystem: boolean;
        operational: boolean;
        message: string;
    }>;
    initializeAccessControl(): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    removeFromMemoryJar(postId: string): Promise<boolean>;
    removeMusicAttachment(musicId: string): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    sendLoveNote(id: string, recipient: Principal, message: string): Promise<string>;
    setDailyChallenge(id: string, prompt: string, category: PostCategory, date: Time): Promise<DailyChallenge>;
    storeKindnessMatches(user: Principal, matches: Array<KindnessMatch>): Promise<void>;
}
import type { DailyChallenge as _DailyChallenge, ExternalBlob as _ExternalBlob, KindnessMatch as _KindnessMatch, MusicAttachment as _MusicAttachment, PhotoAlbumView as _PhotoAlbumView, Post as _Post, PostCategory as _PostCategory, StatusUpdate as _StatusUpdate, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, VideoAlbumView as _VideoAlbumView, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async addPhotoToAlbum(arg0: string, arg1: ExternalBlob): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.addPhotoToAlbum(arg0, await to_candid_ExternalBlob_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPhotoToAlbum(arg0, await to_candid_ExternalBlob_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async addStatusUpdate(arg0: string | null, arg1: ExternalBlob | null, arg2: MusicAttachment | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addStatusUpdate(to_candid_opt_n9(this._uploadFile, this._downloadFile, arg0), await to_candid_opt_n10(this._uploadFile, this._downloadFile, arg1), await to_candid_opt_n11(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addStatusUpdate(to_candid_opt_n9(this._uploadFile, this._downloadFile, arg0), await to_candid_opt_n10(this._uploadFile, this._downloadFile, arg1), await to_candid_opt_n11(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async addToMemoryJar(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.addToMemoryJar(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addToMemoryJar(arg0);
            return result;
        }
    }
    async addVideoToAlbum(arg0: string, arg1: ExternalBlob): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.addVideoToAlbum(arg0, await to_candid_ExternalBlob_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addVideoToAlbum(arg0, await to_candid_ExternalBlob_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n14(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n14(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async attachMusicToStatus(arg0: string, arg1: string, arg2: string, arg3: ExternalBlob): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.attachMusicToStatus(arg0, arg1, arg2, await to_candid_ExternalBlob_n8(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.attachMusicToStatus(arg0, arg1, arg2, await to_candid_ExternalBlob_n8(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async completeDailyChallenge(arg0: string, arg1: string): Promise<ChallengeCompletion> {
        if (this.processError) {
            try {
                const result = await this.actor.completeDailyChallenge(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.completeDailyChallenge(arg0, arg1);
            return result;
        }
    }
    async createPhotoAlbum(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createPhotoAlbum(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPhotoAlbum(arg0, arg1);
            return result;
        }
    }
    async createPost(arg0: string, arg1: string, arg2: string | null, arg3: ExternalBlob | null, arg4: ExternalBlob | null, arg5: PostCategory): Promise<Post> {
        if (this.processError) {
            try {
                const result = await this.actor.createPost(arg0, arg1, to_candid_opt_n9(this._uploadFile, this._downloadFile, arg2), await to_candid_opt_n10(this._uploadFile, this._downloadFile, arg3), await to_candid_opt_n10(this._uploadFile, this._downloadFile, arg4), to_candid_PostCategory_n16(this._uploadFile, this._downloadFile, arg5));
                return from_candid_Post_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPost(arg0, arg1, to_candid_opt_n9(this._uploadFile, this._downloadFile, arg2), await to_candid_opt_n10(this._uploadFile, this._downloadFile, arg3), await to_candid_opt_n10(this._uploadFile, this._downloadFile, arg4), to_candid_PostCategory_n16(this._uploadFile, this._downloadFile, arg5));
            return from_candid_Post_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async createVideoAlbum(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createVideoAlbum(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createVideoAlbum(arg0, arg1);
            return result;
        }
    }
    async getAllMusicAttachments(): Promise<Array<MusicAttachment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMusicAttachments();
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMusicAttachments();
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getChallengeCompletions(arg0: string): Promise<Array<ChallengeCompletion>> {
        if (this.processError) {
            try {
                const result = await this.actor.getChallengeCompletions(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChallengeCompletions(arg0);
            return result;
        }
    }
    async getFriendsStatusUpdates(arg0: Array<Principal>): Promise<Array<StatusUpdate>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFriendsStatusUpdates(arg0);
                return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFriendsStatusUpdates(arg0);
            return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLoveNotesCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getLoveNotesCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLoveNotesCount();
            return result;
        }
    }
    async getMusicAttachment(arg0: string): Promise<MusicAttachment | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMusicAttachment(arg0);
                return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMusicAttachment(arg0);
            return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyLoveNotes(): Promise<Array<LoveNote>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyLoveNotes();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyLoveNotes();
            return result;
        }
    }
    async getMyMemoryJar(): Promise<Array<MemoryJarEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyMemoryJar();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyMemoryJar();
            return result;
        }
    }
    async getMyPhotoAlbums(): Promise<Array<PhotoAlbumView>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyPhotoAlbums();
                return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyPhotoAlbums();
            return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyVideoAlbums(): Promise<Array<VideoAlbumView>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyVideoAlbums();
                return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyVideoAlbums();
            return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRippleChain(arg0: string): Promise<Array<Post>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRippleChain(arg0);
                return from_candid_vec_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRippleChain(arg0);
            return from_candid_vec_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTodaysChallenge(): Promise<DailyChallenge | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTodaysChallenge();
                return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTodaysChallenge();
            return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTopMatches(arg0: Principal): Promise<Array<KindnessMatch>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTopMatches(arg0);
                return from_candid_vec_n48(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTopMatches(arg0);
            return from_candid_vec_n48(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserAlbums(arg0: Principal): Promise<{
        photoAlbums: Array<PhotoAlbumView>;
        videoAlbums: Array<VideoAlbumView>;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserAlbums(arg0);
                return from_candid_record_n52(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserAlbums(arg0);
            return from_candid_record_n52(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserChallengeCompletions(arg0: Principal): Promise<Array<ChallengeCompletion>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserChallengeCompletions(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserChallengeCompletions(arg0);
            return result;
        }
    }
    async getUserPhotoAlbums(arg0: Principal): Promise<Array<PhotoAlbumView>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserPhotoAlbums(arg0);
                return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserPhotoAlbums(arg0);
            return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserStatusUpdates(arg0: Principal): Promise<Array<StatusUpdate>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserStatusUpdates(arg0);
                return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserStatusUpdates(arg0);
            return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserVideoAlbums(arg0: Principal): Promise<Array<VideoAlbumView>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserVideoAlbums(arg0);
                return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserVideoAlbums(arg0);
            return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async healthcheckWithPhotos(): Promise<{
        photoSystem: boolean;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.healthcheckWithPhotos();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.healthcheckWithPhotos();
            return result;
        }
    }
    async healthcheckWithStorageCleanup(): Promise<{
        storageSystem: boolean;
        operational: boolean;
        message: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.healthcheckWithStorageCleanup();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.healthcheckWithStorageCleanup();
            return result;
        }
    }
    async initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeAccessControl();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async removeFromMemoryJar(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.removeFromMemoryJar(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeFromMemoryJar(arg0);
            return result;
        }
    }
    async removeMusicAttachment(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.removeMusicAttachment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeMusicAttachment(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(await to_candid_UserProfile_n53(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(await to_candid_UserProfile_n53(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async sendLoveNote(arg0: string, arg1: Principal, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.sendLoveNote(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendLoveNote(arg0, arg1, arg2);
            return result;
        }
    }
    async setDailyChallenge(arg0: string, arg1: string, arg2: PostCategory, arg3: Time): Promise<DailyChallenge> {
        if (this.processError) {
            try {
                const result = await this.actor.setDailyChallenge(arg0, arg1, to_candid_PostCategory_n16(this._uploadFile, this._downloadFile, arg2), arg3);
                return from_candid_DailyChallenge_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setDailyChallenge(arg0, arg1, to_candid_PostCategory_n16(this._uploadFile, this._downloadFile, arg2), arg3);
            return from_candid_DailyChallenge_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async storeKindnessMatches(arg0: Principal, arg1: Array<KindnessMatch>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.storeKindnessMatches(arg0, to_candid_vec_n55(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.storeKindnessMatches(arg0, to_candid_vec_n55(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_DailyChallenge_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DailyChallenge): DailyChallenge {
    return from_candid_record_n47(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_KindnessMatch_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _KindnessMatch): KindnessMatch {
    return from_candid_record_n50(_uploadFile, _downloadFile, value);
}
async function from_candid_MusicAttachment_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MusicAttachment): Promise<MusicAttachment> {
    return await from_candid_record_n27(_uploadFile, _downloadFile, value);
}
async function from_candid_PhotoAlbumView_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PhotoAlbumView): Promise<PhotoAlbumView> {
    return await from_candid_record_n39(_uploadFile, _downloadFile, value);
}
function from_candid_PostCategory_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PostCategory): PostCategory {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
async function from_candid_Post_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Post): Promise<Post> {
    return await from_candid_record_n19(_uploadFile, _downloadFile, value);
}
async function from_candid_StatusUpdate_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StatusUpdate): Promise<StatusUpdate> {
    return await from_candid_record_n35(_uploadFile, _downloadFile, value);
}
async function from_candid_UserProfile_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): Promise<UserProfile> {
    return await from_candid_record_n30(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n32(_uploadFile, _downloadFile, value);
}
async function from_candid_VideoAlbumView_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VideoAlbumView): Promise<VideoAlbumView> {
    return await from_candid_record_n43(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n22(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): Promise<UserProfile | null> {
    return value.length === 0 ? null : await from_candid_UserProfile_n29(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_MusicAttachment]): Promise<MusicAttachment | null> {
    return value.length === 0 ? null : await from_candid_MusicAttachment_n26(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_DailyChallenge]): DailyChallenge | null {
    return value.length === 0 ? null : from_candid_DailyChallenge_n46(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    parentPostId: [] | [string];
    video: [] | [_ExternalBlob];
    author: Principal;
    likes: bigint;
    timestamp: _Time;
    caption: string;
    category: _PostCategory;
    comments: bigint;
    photo: [] | [_ExternalBlob];
    isFlagged: boolean;
}): Promise<{
    id: string;
    parentPostId?: string;
    video?: ExternalBlob;
    author: Principal;
    likes: bigint;
    timestamp: Time;
    caption: string;
    category: PostCategory;
    comments: bigint;
    photo?: ExternalBlob;
    isFlagged: boolean;
}> {
    return {
        id: value.id,
        parentPostId: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.parentPostId)),
        video: record_opt_to_undefined(await from_candid_opt_n21(_uploadFile, _downloadFile, value.video)),
        author: value.author,
        likes: value.likes,
        timestamp: value.timestamp,
        caption: value.caption,
        category: from_candid_PostCategory_n23(_uploadFile, _downloadFile, value.category),
        comments: value.comments,
        photo: record_opt_to_undefined(await from_candid_opt_n21(_uploadFile, _downloadFile, value.photo)),
        isFlagged: value.isFlagged
    };
}
async function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    audioFile: _ExternalBlob;
    artist: string;
}): Promise<{
    id: string;
    title: string;
    audioFile: ExternalBlob;
    artist: string;
}> {
    return {
        id: value.id,
        title: value.title,
        audioFile: await from_candid_ExternalBlob_n22(_uploadFile, _downloadFile, value.audioFile),
        artist: value.artist
    };
}
async function from_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bio: string;
    principal: Principal;
    statusImage: [] | [_ExternalBlob];
    name: string;
    layoutPreferences: [] | [string];
    statusText: [] | [string];
    followers: bigint;
    following: bigint;
    profilePicture: [] | [_ExternalBlob];
}): Promise<{
    bio: string;
    principal: Principal;
    statusImage?: ExternalBlob;
    name: string;
    layoutPreferences?: string;
    statusText?: string;
    followers: bigint;
    following: bigint;
    profilePicture?: ExternalBlob;
}> {
    return {
        bio: value.bio,
        principal: value.principal,
        statusImage: record_opt_to_undefined(await from_candid_opt_n21(_uploadFile, _downloadFile, value.statusImage)),
        name: value.name,
        layoutPreferences: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.layoutPreferences)),
        statusText: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.statusText)),
        followers: value.followers,
        following: value.following,
        profilePicture: record_opt_to_undefined(await from_candid_opt_n21(_uploadFile, _downloadFile, value.profilePicture))
    };
}
async function from_candid_record_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    music: [] | [_MusicAttachment];
    text: [] | [string];
    timestamp: _Time;
    image: [] | [_ExternalBlob];
}): Promise<{
    music?: MusicAttachment;
    text?: string;
    timestamp: Time;
    image?: ExternalBlob;
}> {
    return {
        music: record_opt_to_undefined(await from_candid_opt_n36(_uploadFile, _downloadFile, value.music)),
        text: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.text)),
        timestamp: value.timestamp,
        image: record_opt_to_undefined(await from_candid_opt_n21(_uploadFile, _downloadFile, value.image))
    };
}
async function from_candid_record_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    name: string;
    photos: Array<_ExternalBlob>;
}): Promise<{
    id: string;
    name: string;
    photos: Array<ExternalBlob>;
}> {
    return {
        id: value.id,
        name: value.name,
        photos: await from_candid_vec_n40(_uploadFile, _downloadFile, value.photos)
    };
}
async function from_candid_record_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    name: string;
    videos: Array<_ExternalBlob>;
}): Promise<{
    id: string;
    name: string;
    videos: Array<ExternalBlob>;
}> {
    return {
        id: value.id,
        name: value.name,
        videos: await from_candid_vec_n40(_uploadFile, _downloadFile, value.videos)
    };
}
function from_candid_record_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    date: _Time;
    category: _PostCategory;
    prompt: string;
}): {
    id: string;
    date: Time;
    category: PostCategory;
    prompt: string;
} {
    return {
        id: value.id,
        date: value.date,
        category: from_candid_PostCategory_n23(_uploadFile, _downloadFile, value.category),
        prompt: value.prompt
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_record_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    sharedCategories: Array<_PostCategory>;
    withUser: Principal;
    compatibilityScore: bigint;
    reason: string;
}): {
    sharedCategories: Array<PostCategory>;
    withUser: Principal;
    compatibilityScore: bigint;
    reason: string;
} {
    return {
        sharedCategories: from_candid_vec_n51(_uploadFile, _downloadFile, value.sharedCategories),
        withUser: value.withUser,
        compatibilityScore: value.compatibilityScore,
        reason: value.reason
    };
}
async function from_candid_record_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    photoAlbums: Array<_PhotoAlbumView>;
    videoAlbums: Array<_VideoAlbumView>;
}): Promise<{
    photoAlbums: Array<PhotoAlbumView>;
    videoAlbums: Array<VideoAlbumView>;
}> {
    return {
        photoAlbums: await from_candid_vec_n37(_uploadFile, _downloadFile, value.photoAlbums),
        videoAlbums: await from_candid_vec_n41(_uploadFile, _downloadFile, value.videoAlbums)
    };
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    other: null;
} | {
    actsOfKindness: null;
} | {
    environmental: null;
} | {
    communityService: null;
}): PostCategory {
    return "other" in value ? PostCategory.other : "actsOfKindness" in value ? PostCategory.actsOfKindness : "environmental" in value ? PostCategory.environmental : "communityService" in value ? PostCategory.communityService : value;
}
function from_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
async function from_candid_vec_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MusicAttachment>): Promise<Array<MusicAttachment>> {
    return await Promise.all(value.map(async (x)=>await from_candid_MusicAttachment_n26(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_StatusUpdate>): Promise<Array<StatusUpdate>> {
    return await Promise.all(value.map(async (x)=>await from_candid_StatusUpdate_n34(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PhotoAlbumView>): Promise<Array<PhotoAlbumView>> {
    return await Promise.all(value.map(async (x)=>await from_candid_PhotoAlbumView_n38(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ExternalBlob>): Promise<Array<ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await from_candid_ExternalBlob_n22(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_VideoAlbumView>): Promise<Array<VideoAlbumView>> {
    return await Promise.all(value.map(async (x)=>await from_candid_VideoAlbumView_n42(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Post>): Promise<Array<Post>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Post_n18(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_KindnessMatch>): Array<KindnessMatch> {
    return value.map((x)=>from_candid_KindnessMatch_n49(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PostCategory>): Array<PostCategory> {
    return value.map((x)=>from_candid_PostCategory_n23(_uploadFile, _downloadFile, x));
}
async function to_candid_ExternalBlob_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_KindnessMatch_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: KindnessMatch): _KindnessMatch {
    return to_candid_record_n57(_uploadFile, _downloadFile, value);
}
async function to_candid_MusicAttachment_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MusicAttachment): Promise<_MusicAttachment> {
    return await to_candid_record_n13(_uploadFile, _downloadFile, value);
}
function to_candid_PostCategory_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PostCategory): _PostCategory {
    return to_candid_variant_n17(_uploadFile, _downloadFile, value);
}
async function to_candid_UserProfile_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): Promise<_UserProfile> {
    return await to_candid_record_n54(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
async function to_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob | null): Promise<[] | [_ExternalBlob]> {
    return value === null ? candid_none() : candid_some(await to_candid_ExternalBlob_n8(_uploadFile, _downloadFile, value));
}
async function to_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MusicAttachment | null): Promise<[] | [_MusicAttachment]> {
    return value === null ? candid_none() : candid_some(await to_candid_MusicAttachment_n12(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
async function to_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    audioFile: ExternalBlob;
    artist: string;
}): Promise<{
    id: string;
    title: string;
    audioFile: _ExternalBlob;
    artist: string;
}> {
    return {
        id: value.id,
        title: value.title,
        audioFile: await to_candid_ExternalBlob_n8(_uploadFile, _downloadFile, value.audioFile),
        artist: value.artist
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
async function to_candid_record_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bio: string;
    principal: Principal;
    statusImage?: ExternalBlob;
    name: string;
    layoutPreferences?: string;
    statusText?: string;
    followers: bigint;
    following: bigint;
    profilePicture?: ExternalBlob;
}): Promise<{
    bio: string;
    principal: Principal;
    statusImage: [] | [_ExternalBlob];
    name: string;
    layoutPreferences: [] | [string];
    statusText: [] | [string];
    followers: bigint;
    following: bigint;
    profilePicture: [] | [_ExternalBlob];
}> {
    return {
        bio: value.bio,
        principal: value.principal,
        statusImage: value.statusImage ? candid_some(await to_candid_ExternalBlob_n8(_uploadFile, _downloadFile, value.statusImage)) : candid_none(),
        name: value.name,
        layoutPreferences: value.layoutPreferences ? candid_some(value.layoutPreferences) : candid_none(),
        statusText: value.statusText ? candid_some(value.statusText) : candid_none(),
        followers: value.followers,
        following: value.following,
        profilePicture: value.profilePicture ? candid_some(await to_candid_ExternalBlob_n8(_uploadFile, _downloadFile, value.profilePicture)) : candid_none()
    };
}
function to_candid_record_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    sharedCategories: Array<PostCategory>;
    withUser: Principal;
    compatibilityScore: bigint;
    reason: string;
}): {
    sharedCategories: Array<_PostCategory>;
    withUser: Principal;
    compatibilityScore: bigint;
    reason: string;
} {
    return {
        sharedCategories: to_candid_vec_n58(_uploadFile, _downloadFile, value.sharedCategories),
        withUser: value.withUser,
        compatibilityScore: value.compatibilityScore,
        reason: value.reason
    };
}
function to_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PostCategory): {
    other: null;
} | {
    actsOfKindness: null;
} | {
    environmental: null;
} | {
    communityService: null;
} {
    return value == PostCategory.other ? {
        other: null
    } : value == PostCategory.actsOfKindness ? {
        actsOfKindness: null
    } : value == PostCategory.environmental ? {
        environmental: null
    } : value == PostCategory.communityService ? {
        communityService: null
    } : value;
}
function to_candid_vec_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<KindnessMatch>): Array<_KindnessMatch> {
    return value.map((x)=>to_candid_KindnessMatch_n56(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<PostCategory>): Array<_PostCategory> {
    return value.map((x)=>to_candid_PostCategory_n16(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
