import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'en' | 'es' | 'fr' | 'de' | 'zh' | 'ar' | 'ja' | 'pt' | 'ru' | 'hi';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  en: {
    // App
    'app.title': 'Deeds',
    'app.tagline': 'Connect. Share. Inspire.',
    'app.description': 'Your hub for inspiring stories, positive challenges, and community connection',
    
    // Navigation
    'nav.home': 'Home',
    'nav.feed': 'Feed',
    'nav.discover': 'Discover',
    'nav.market': 'Market',
    'nav.blogs': 'Blogs',
    'nav.messages': 'Messages',
    'nav.profile': 'Profile',
    
    // Actions
    'action.login': 'Login',
    'action.logout': 'Logout',
    'action.save': 'Save',
    'action.cancel': 'Cancel',
    'action.delete': 'Delete',
    'action.edit': 'Edit',
    'action.share': 'Share',
    'action.search': 'Search',
    
    // Profile
    'profile.followers': 'Followers',
    'profile.following': 'Following',
    'profile.deeds': 'Deeds',
    'profile.status': 'Status',
    'profile.updateStatus': 'Update Status',
    'profile.mediaGallery': 'Media Gallery',
    'profile.videos': 'Videos',
    'profile.photos': 'Photos',
    'profile.notFound': 'Profile not found',
    
    // Reactions
    'reaction.spark': 'Spark',
    'reaction.inspire': 'Inspire',
    'reaction.comment': 'Comment',
    'reaction.share': 'Share',
    'reaction.sparked': 'Sparked!',
    'reaction.inspired': 'Inspired!',
    
    // DeedsBar
    'deedsbar.title': 'Your Deeds Bar',
    'deedsbar.sessionTime': 'Session Time',
    'deedsbar.battery': 'Battery',
    'deedsbar.dailyUsage': 'Today\'s Total Usage',
    'deedsbar.dailyLimit': 'Daily limit: 17 hours',
    'deedsbar.remaining': 'remaining',
    'deedsbar.limit': 'limit',
    
    // Feed
    'feed.following': 'Following',
    'feed.forYou': 'For You',
    'feed.all': 'All',
    'feed.videos': 'Videos',
    'feed.text': 'Text',
    'feed.noPosts': 'No posts yet',
    
    // Settings
    'settings.language': 'Language',
    'settings.selectLanguage': 'Select Language',
  },
  es: {
    'app.title': 'Deeds',
    'app.tagline': 'Conectar. Compartir. Inspirar.',
    'app.description': 'Tu centro para historias inspiradoras, desafíos positivos y conexión comunitaria',
    'nav.home': 'Inicio',
    'nav.feed': 'Feed',
    'nav.discover': 'Descubrir',
    'nav.market': 'Mercado',
    'nav.blogs': 'Blogs',
    'nav.messages': 'Mensajes',
    'nav.profile': 'Perfil',
    'action.login': 'Iniciar sesión',
    'action.logout': 'Cerrar sesión',
    'action.save': 'Guardar',
    'action.cancel': 'Cancelar',
    'action.delete': 'Eliminar',
    'action.edit': 'Editar',
    'action.share': 'Compartir',
    'action.search': 'Buscar',
    'profile.followers': 'Seguidores',
    'profile.following': 'Siguiendo',
    'profile.deeds': 'Acciones',
    'profile.status': 'Estado',
    'profile.updateStatus': 'Actualizar Estado',
    'profile.mediaGallery': 'Galería de Medios',
    'profile.videos': 'Videos',
    'profile.photos': 'Fotos',
    'profile.notFound': 'Perfil no encontrado',
    'reaction.spark': 'Chispa',
    'reaction.inspire': 'Inspirar',
    'reaction.comment': 'Comentar',
    'reaction.share': 'Compartir',
    'reaction.sparked': '¡Chispa!',
    'reaction.inspired': '¡Inspirado!',
    'deedsbar.title': 'Tu Barra de Deeds',
    'deedsbar.sessionTime': 'Tiempo de Sesión',
    'deedsbar.battery': 'Batería',
    'deedsbar.dailyUsage': 'Uso Total de Hoy',
    'deedsbar.dailyLimit': 'Límite diario: 17 horas',
    'deedsbar.remaining': 'restante',
    'deedsbar.limit': 'límite',
    'feed.following': 'Siguiendo',
    'feed.forYou': 'Para Ti',
    'feed.all': 'Todo',
    'feed.videos': 'Videos',
    'feed.text': 'Texto',
    'feed.noPosts': 'Aún no hay publicaciones',
    'settings.language': 'Idioma',
    'settings.selectLanguage': 'Seleccionar Idioma',
  },
  fr: {
    'app.title': 'Deeds',
    'app.tagline': 'Connecter. Partager. Inspirer.',
    'app.description': 'Votre centre pour des histoires inspirantes, des défis positifs et la connexion communautaire',
    'nav.home': 'Accueil',
    'nav.feed': 'Fil',
    'nav.discover': 'Découvrir',
    'nav.market': 'Marché',
    'nav.blogs': 'Blogs',
    'nav.messages': 'Messages',
    'nav.profile': 'Profil',
    'action.login': 'Connexion',
    'action.logout': 'Déconnexion',
    'action.save': 'Enregistrer',
    'action.cancel': 'Annuler',
    'action.delete': 'Supprimer',
    'action.edit': 'Modifier',
    'action.share': 'Partager',
    'action.search': 'Rechercher',
    'profile.followers': 'Abonnés',
    'profile.following': 'Abonnements',
    'profile.deeds': 'Actions',
    'profile.status': 'Statut',
    'profile.updateStatus': 'Mettre à jour le statut',
    'profile.mediaGallery': 'Galerie Média',
    'profile.videos': 'Vidéos',
    'profile.photos': 'Photos',
    'profile.notFound': 'Profil non trouvé',
    'reaction.spark': 'Étincelle',
    'reaction.inspire': 'Inspirer',
    'reaction.comment': 'Commenter',
    'reaction.share': 'Partager',
    'reaction.sparked': 'Étincelle!',
    'reaction.inspired': 'Inspiré!',
    'deedsbar.title': 'Votre Barre Deeds',
    'deedsbar.sessionTime': 'Temps de Session',
    'deedsbar.battery': 'Batterie',
    'deedsbar.dailyUsage': 'Usage Total Aujourd\'hui',
    'deedsbar.dailyLimit': 'Limite quotidienne: 17 heures',
    'deedsbar.remaining': 'restant',
    'deedsbar.limit': 'limite',
    'feed.following': 'Abonnements',
    'feed.forYou': 'Pour Vous',
    'feed.all': 'Tout',
    'feed.videos': 'Vidéos',
    'feed.text': 'Texte',
    'feed.noPosts': 'Pas encore de publications',
    'settings.language': 'Langue',
    'settings.selectLanguage': 'Sélectionner la Langue',
  },
  de: {
    'app.title': 'Deeds',
    'app.tagline': 'Verbinden. Teilen. Inspirieren.',
    'app.description': 'Ihr Zentrum für inspirierende Geschichten, positive Herausforderungen und Gemeinschaftsverbindung',
    'nav.home': 'Startseite',
    'nav.feed': 'Feed',
    'nav.discover': 'Entdecken',
    'nav.market': 'Markt',
    'nav.blogs': 'Blogs',
    'nav.messages': 'Nachrichten',
    'nav.profile': 'Profil',
    'action.login': 'Anmelden',
    'action.logout': 'Abmelden',
    'action.save': 'Speichern',
    'action.cancel': 'Abbrechen',
    'action.delete': 'Löschen',
    'action.edit': 'Bearbeiten',
    'action.share': 'Teilen',
    'action.search': 'Suchen',
    'profile.followers': 'Follower',
    'profile.following': 'Folge ich',
    'profile.deeds': 'Taten',
    'profile.status': 'Status',
    'profile.updateStatus': 'Status aktualisieren',
    'profile.mediaGallery': 'Mediengalerie',
    'profile.videos': 'Videos',
    'profile.photos': 'Fotos',
    'profile.notFound': 'Profil nicht gefunden',
    'reaction.spark': 'Funke',
    'reaction.inspire': 'Inspirieren',
    'reaction.comment': 'Kommentieren',
    'reaction.share': 'Teilen',
    'reaction.sparked': 'Gefunkt!',
    'reaction.inspired': 'Inspiriert!',
    'deedsbar.title': 'Ihre Deeds-Leiste',
    'deedsbar.sessionTime': 'Sitzungszeit',
    'deedsbar.battery': 'Batterie',
    'deedsbar.dailyUsage': 'Heutige Gesamtnutzung',
    'deedsbar.dailyLimit': 'Tageslimit: 17 Stunden',
    'deedsbar.remaining': 'verbleibend',
    'deedsbar.limit': 'Limit',
    'feed.following': 'Folge ich',
    'feed.forYou': 'Für Dich',
    'feed.all': 'Alle',
    'feed.videos': 'Videos',
    'feed.text': 'Text',
    'feed.noPosts': 'Noch keine Beiträge',
    'settings.language': 'Sprache',
    'settings.selectLanguage': 'Sprache auswählen',
  },
  zh: {
    'app.title': 'Deeds',
    'app.tagline': '连接。分享。启发。',
    'app.description': '您的灵感故事、积极挑战和社区连接中心',
    'nav.home': '首页',
    'nav.feed': '动态',
    'nav.discover': '发现',
    'nav.market': '市场',
    'nav.blogs': '博客',
    'nav.messages': '消息',
    'nav.profile': '个人资料',
    'action.login': '登录',
    'action.logout': '登出',
    'action.save': '保存',
    'action.cancel': '取消',
    'action.delete': '删除',
    'action.edit': '编辑',
    'action.share': '分享',
    'action.search': '搜索',
    'profile.followers': '粉丝',
    'profile.following': '关注',
    'profile.deeds': '善行',
    'profile.status': '状态',
    'profile.updateStatus': '更新状态',
    'profile.mediaGallery': '媒体库',
    'profile.videos': '视频',
    'profile.photos': '照片',
    'profile.notFound': '未找到个人资料',
    'reaction.spark': '火花',
    'reaction.inspire': '启发',
    'reaction.comment': '评论',
    'reaction.share': '分享',
    'reaction.sparked': '已点亮！',
    'reaction.inspired': '已启发！',
    'deedsbar.title': '您的 Deeds 栏',
    'deedsbar.sessionTime': '会话时间',
    'deedsbar.battery': '电量',
    'deedsbar.dailyUsage': '今日总使用量',
    'deedsbar.dailyLimit': '每日限制：17小时',
    'deedsbar.remaining': '剩余',
    'deedsbar.limit': '限制',
    'feed.following': '关注',
    'feed.forYou': '为你推荐',
    'feed.all': '全部',
    'feed.videos': '视频',
    'feed.text': '文字',
    'feed.noPosts': '暂无帖子',
    'settings.language': '语言',
    'settings.selectLanguage': '选择语言',
  },
  ar: {
    'app.title': 'Deeds',
    'app.tagline': 'اتصل. شارك. ألهم.',
    'app.description': 'مركزك للقصص الملهمة والتحديات الإيجابية والتواصل المجتمعي',
    'nav.home': 'الرئيسية',
    'nav.feed': 'التغذية',
    'nav.discover': 'اكتشف',
    'nav.market': 'السوق',
    'nav.blogs': 'المدونات',
    'nav.messages': 'الرسائل',
    'nav.profile': 'الملف الشخصي',
    'action.login': 'تسجيل الدخول',
    'action.logout': 'تسجيل الخروج',
    'action.save': 'حفظ',
    'action.cancel': 'إلغاء',
    'action.delete': 'حذف',
    'action.edit': 'تعديل',
    'action.share': 'مشاركة',
    'action.search': 'بحث',
    'profile.followers': 'المتابعون',
    'profile.following': 'المتابَعون',
    'profile.deeds': 'الأعمال',
    'profile.status': 'الحالة',
    'profile.updateStatus': 'تحديث الحالة',
    'profile.mediaGallery': 'معرض الوسائط',
    'profile.videos': 'الفيديوهات',
    'profile.photos': 'الصور',
    'profile.notFound': 'الملف الشخصي غير موجود',
    'reaction.spark': 'شرارة',
    'reaction.inspire': 'ألهم',
    'reaction.comment': 'تعليق',
    'reaction.share': 'مشاركة',
    'reaction.sparked': 'أشعلت!',
    'reaction.inspired': 'ألهمت!',
    'deedsbar.title': 'شريط Deeds الخاص بك',
    'deedsbar.sessionTime': 'وقت الجلسة',
    'deedsbar.battery': 'البطارية',
    'deedsbar.dailyUsage': 'الاستخدام الإجمالي اليوم',
    'deedsbar.dailyLimit': 'الحد اليومي: 17 ساعة',
    'deedsbar.remaining': 'متبقي',
    'deedsbar.limit': 'الحد',
    'feed.following': 'المتابَعون',
    'feed.forYou': 'لك',
    'feed.all': 'الكل',
    'feed.videos': 'الفيديوهات',
    'feed.text': 'النص',
    'feed.noPosts': 'لا توجد منشورات بعد',
    'settings.language': 'اللغة',
    'settings.selectLanguage': 'اختر اللغة',
  },
  ja: {
    'app.title': 'Deeds',
    'app.tagline': 'つながる。共有する。インスパイアする。',
    'app.description': 'インスピレーションあふれるストーリー、ポジティブなチャレンジ、コミュニティのつながりのハブ',
    'nav.home': 'ホーム',
    'nav.feed': 'フィード',
    'nav.discover': '発見',
    'nav.market': 'マーケット',
    'nav.blogs': 'ブログ',
    'nav.messages': 'メッセージ',
    'nav.profile': 'プロフィール',
    'action.login': 'ログイン',
    'action.logout': 'ログアウト',
    'action.save': '保存',
    'action.cancel': 'キャンセル',
    'action.delete': '削除',
    'action.edit': '編集',
    'action.share': '共有',
    'action.search': '検索',
    'profile.followers': 'フォロワー',
    'profile.following': 'フォロー中',
    'profile.deeds': '善行',
    'profile.status': 'ステータス',
    'profile.updateStatus': 'ステータスを更新',
    'profile.mediaGallery': 'メディアギャラリー',
    'profile.videos': '動画',
    'profile.photos': '写真',
    'profile.notFound': 'プロフィールが見つかりません',
    'reaction.spark': 'スパーク',
    'reaction.inspire': 'インスパイア',
    'reaction.comment': 'コメント',
    'reaction.share': '共有',
    'reaction.sparked': 'スパークした！',
    'reaction.inspired': 'インスパイアされた！',
    'deedsbar.title': 'あなたのDeedsバー',
    'deedsbar.sessionTime': 'セッション時間',
    'deedsbar.battery': 'バッテリー',
    'deedsbar.dailyUsage': '今日の合計使用量',
    'deedsbar.dailyLimit': '1日の制限：17時間',
    'deedsbar.remaining': '残り',
    'deedsbar.limit': '制限',
    'feed.following': 'フォロー中',
    'feed.forYou': 'おすすめ',
    'feed.all': 'すべて',
    'feed.videos': '動画',
    'feed.text': 'テキスト',
    'feed.noPosts': 'まだ投稿がありません',
    'settings.language': '言語',
    'settings.selectLanguage': '言語を選択',
  },
  pt: {
    'app.title': 'Deeds',
    'app.tagline': 'Conectar. Compartilhar. Inspirar.',
    'app.description': 'Seu centro para histórias inspiradoras, desafios positivos e conexão comunitária',
    'nav.home': 'Início',
    'nav.feed': 'Feed',
    'nav.discover': 'Descobrir',
    'nav.market': 'Mercado',
    'nav.blogs': 'Blogs',
    'nav.messages': 'Mensagens',
    'nav.profile': 'Perfil',
    'action.login': 'Entrar',
    'action.logout': 'Sair',
    'action.save': 'Salvar',
    'action.cancel': 'Cancelar',
    'action.delete': 'Excluir',
    'action.edit': 'Editar',
    'action.share': 'Compartilhar',
    'action.search': 'Pesquisar',
    'profile.followers': 'Seguidores',
    'profile.following': 'Seguindo',
    'profile.deeds': 'Ações',
    'profile.status': 'Status',
    'profile.updateStatus': 'Atualizar Status',
    'profile.mediaGallery': 'Galeria de Mídia',
    'profile.videos': 'Vídeos',
    'profile.photos': 'Fotos',
    'profile.notFound': 'Perfil não encontrado',
    'reaction.spark': 'Faísca',
    'reaction.inspire': 'Inspirar',
    'reaction.comment': 'Comentar',
    'reaction.share': 'Compartilhar',
    'reaction.sparked': 'Faiscou!',
    'reaction.inspired': 'Inspirado!',
    'deedsbar.title': 'Sua Barra Deeds',
    'deedsbar.sessionTime': 'Tempo de Sessão',
    'deedsbar.battery': 'Bateria',
    'deedsbar.dailyUsage': 'Uso Total Hoje',
    'deedsbar.dailyLimit': 'Limite diário: 17 horas',
    'deedsbar.remaining': 'restante',
    'deedsbar.limit': 'limite',
    'feed.following': 'Seguindo',
    'feed.forYou': 'Para Você',
    'feed.all': 'Tudo',
    'feed.videos': 'Vídeos',
    'feed.text': 'Texto',
    'feed.noPosts': 'Ainda não há postagens',
    'settings.language': 'Idioma',
    'settings.selectLanguage': 'Selecionar Idioma',
  },
  ru: {
    'app.title': 'Deeds',
    'app.tagline': 'Соединяйтесь. Делитесь. Вдохновляйте.',
    'app.description': 'Ваш центр вдохновляющих историй, позитивных вызовов и общественных связей',
    'nav.home': 'Главная',
    'nav.feed': 'Лента',
    'nav.discover': 'Открыть',
    'nav.market': 'Рынок',
    'nav.blogs': 'Блоги',
    'nav.messages': 'Сообщения',
    'nav.profile': 'Профиль',
    'action.login': 'Войти',
    'action.logout': 'Выйти',
    'action.save': 'Сохранить',
    'action.cancel': 'Отмена',
    'action.delete': 'Удалить',
    'action.edit': 'Редактировать',
    'action.share': 'Поделиться',
    'action.search': 'Поиск',
    'profile.followers': 'Подписчики',
    'profile.following': 'Подписки',
    'profile.deeds': 'Дела',
    'profile.status': 'Статус',
    'profile.updateStatus': 'Обновить статус',
    'profile.mediaGallery': 'Медиагалерея',
    'profile.videos': 'Видео',
    'profile.photos': 'Фото',
    'profile.notFound': 'Профиль не найден',
    'reaction.spark': 'Искра',
    'reaction.inspire': 'Вдохновить',
    'reaction.comment': 'Комментарий',
    'reaction.share': 'Поделиться',
    'reaction.sparked': 'Зажжено!',
    'reaction.inspired': 'Вдохновлено!',
    'deedsbar.title': 'Ваша панель Deeds',
    'deedsbar.sessionTime': 'Время сеанса',
    'deedsbar.battery': 'Батарея',
    'deedsbar.dailyUsage': 'Общее использование сегодня',
    'deedsbar.dailyLimit': 'Дневной лимит: 17 часов',
    'deedsbar.remaining': 'осталось',
    'deedsbar.limit': 'лимит',
    'feed.following': 'Подписки',
    'feed.forYou': 'Для вас',
    'feed.all': 'Все',
    'feed.videos': 'Видео',
    'feed.text': 'Текст',
    'feed.noPosts': 'Пока нет постов',
    'settings.language': 'Язык',
    'settings.selectLanguage': 'Выбрать язык',
  },
  hi: {
    'app.title': 'Deeds',
    'app.tagline': 'जुड़ें। साझा करें। प्रेरित करें।',
    'app.description': 'प्रेरक कहानियों, सकारात्मक चुनौतियों और सामुदायिक संबंध के लिए आपका केंद्र',
    'nav.home': 'होम',
    'nav.feed': 'फ़ीड',
    'nav.discover': 'खोजें',
    'nav.market': 'बाज़ार',
    'nav.blogs': 'ब्लॉग',
    'nav.messages': 'संदेश',
    'nav.profile': 'प्रोफ़ाइल',
    'action.login': 'लॉगिन',
    'action.logout': 'लॉगआउट',
    'action.save': 'सहेजें',
    'action.cancel': 'रद्द करें',
    'action.delete': 'हटाएं',
    'action.edit': 'संपादित करें',
    'action.share': 'साझा करें',
    'action.search': 'खोजें',
    'profile.followers': 'फ़ॉलोअर्स',
    'profile.following': 'फ़ॉलोइंग',
    'profile.deeds': 'कर्म',
    'profile.status': 'स्थिति',
    'profile.updateStatus': 'स्थिति अपडेट करें',
    'profile.mediaGallery': 'मीडिया गैलरी',
    'profile.videos': 'वीडियो',
    'profile.photos': 'फ़ोटो',
    'profile.notFound': 'प्रोफ़ाइल नहीं मिली',
    'reaction.spark': 'स्पार्क',
    'reaction.inspire': 'प्रेरित करें',
    'reaction.comment': 'टिप्पणी',
    'reaction.share': 'साझा करें',
    'reaction.sparked': 'स्पार्क किया!',
    'reaction.inspired': 'प्रेरित!',
    'deedsbar.title': 'आपका Deeds बार',
    'deedsbar.sessionTime': 'सत्र समय',
    'deedsbar.battery': 'बैटरी',
    'deedsbar.dailyUsage': 'आज का कुल उपयोग',
    'deedsbar.dailyLimit': 'दैनिक सीमा: 17 घंटे',
    'deedsbar.remaining': 'शेष',
    'deedsbar.limit': 'सीमा',
    'feed.following': 'फ़ॉलोइंग',
    'feed.forYou': 'आपके लिए',
    'feed.all': 'सभी',
    'feed.videos': 'वीडियो',
    'feed.text': 'टेक्स्ट',
    'feed.noPosts': 'अभी तक कोई पोस्ट नहीं',
    'settings.language': 'भाषा',
    'settings.selectLanguage': 'भाषा चुनें',
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('deeds-language');
    if (saved && saved in translations) {
      return saved as Language;
    }
    // Auto-detect browser language
    const browserLang = navigator.language.split('-')[0];
    return (browserLang in translations ? browserLang : 'en') as Language;
  });

  useEffect(() => {
    localStorage.setItem('deeds-language', language);
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
}
