/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const MusicAttachment = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'audioFile' : ExternalBlob,
  'artist' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const ChallengeCompletion = IDL.Record({
  'id' : IDL.Text,
  'user' : IDL.Principal,
  'challengeId' : IDL.Text,
  'timestamp' : Time,
  'postId' : IDL.Text,
});
export const PostCategory = IDL.Variant({
  'other' : IDL.Null,
  'actsOfKindness' : IDL.Null,
  'environmental' : IDL.Null,
  'communityService' : IDL.Null,
});
export const Post = IDL.Record({
  'id' : IDL.Text,
  'parentPostId' : IDL.Opt(IDL.Text),
  'video' : IDL.Opt(ExternalBlob),
  'author' : IDL.Principal,
  'likes' : IDL.Nat,
  'timestamp' : Time,
  'caption' : IDL.Text,
  'category' : PostCategory,
  'comments' : IDL.Nat,
  'photo' : IDL.Opt(ExternalBlob),
  'isFlagged' : IDL.Bool,
});
export const UserProfile = IDL.Record({
  'bio' : IDL.Text,
  'principal' : IDL.Principal,
  'statusImage' : IDL.Opt(ExternalBlob),
  'name' : IDL.Text,
  'layoutPreferences' : IDL.Opt(IDL.Text),
  'statusText' : IDL.Opt(IDL.Text),
  'followers' : IDL.Nat,
  'following' : IDL.Nat,
  'profilePicture' : IDL.Opt(ExternalBlob),
});
export const StatusUpdate = IDL.Record({
  'music' : IDL.Opt(MusicAttachment),
  'text' : IDL.Opt(IDL.Text),
  'timestamp' : Time,
  'image' : IDL.Opt(ExternalBlob),
});
export const LoveNote = IDL.Record({
  'id' : IDL.Text,
  'recipient' : IDL.Principal,
  'sender' : IDL.Principal,
  'message' : IDL.Text,
  'timestamp' : Time,
});
export const MemoryJarEntry = IDL.Record({
  'savedAt' : Time,
  'postId' : IDL.Text,
});
export const PhotoAlbumView = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'photos' : IDL.Vec(ExternalBlob),
});
export const VideoAlbumView = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'videos' : IDL.Vec(ExternalBlob),
});
export const DailyChallenge = IDL.Record({
  'id' : IDL.Text,
  'date' : Time,
  'category' : PostCategory,
  'prompt' : IDL.Text,
});
export const KindnessMatch = IDL.Record({
  'sharedCategories' : IDL.Vec(PostCategory),
  'withUser' : IDL.Principal,
  'compatibilityScore' : IDL.Nat,
  'reason' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addPhotoToAlbum' : IDL.Func([IDL.Text, ExternalBlob], [IDL.Bool], []),
  'addStatusUpdate' : IDL.Func(
      [IDL.Opt(IDL.Text), IDL.Opt(ExternalBlob), IDL.Opt(MusicAttachment)],
      [],
      [],
    ),
  'addToMemoryJar' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'addVideoToAlbum' : IDL.Func([IDL.Text, ExternalBlob], [IDL.Bool], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'attachMusicToStatus' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, ExternalBlob],
      [],
      [],
    ),
  'completeDailyChallenge' : IDL.Func(
      [IDL.Text, IDL.Text],
      [ChallengeCompletion],
      [],
    ),
  'createPhotoAlbum' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'createPost' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Opt(ExternalBlob),
        IDL.Opt(ExternalBlob),
        PostCategory,
      ],
      [Post],
      [],
    ),
  'createVideoAlbum' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'getAllMusicAttachments' : IDL.Func(
      [],
      [IDL.Vec(MusicAttachment)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getChallengeCompletions' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ChallengeCompletion)],
      ['query'],
    ),
  'getFriendsStatusUpdates' : IDL.Func(
      [IDL.Vec(IDL.Principal)],
      [IDL.Vec(StatusUpdate)],
      ['query'],
    ),
  'getLoveNotesCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getMusicAttachment' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(MusicAttachment)],
      ['query'],
    ),
  'getMyLoveNotes' : IDL.Func([], [IDL.Vec(LoveNote)], ['query']),
  'getMyMemoryJar' : IDL.Func([], [IDL.Vec(MemoryJarEntry)], ['query']),
  'getMyPhotoAlbums' : IDL.Func([], [IDL.Vec(PhotoAlbumView)], ['query']),
  'getMyVideoAlbums' : IDL.Func([], [IDL.Vec(VideoAlbumView)], ['query']),
  'getRippleChain' : IDL.Func([IDL.Text], [IDL.Vec(Post)], ['query']),
  'getTodaysChallenge' : IDL.Func([], [IDL.Opt(DailyChallenge)], ['query']),
  'getTopMatches' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(KindnessMatch)],
      ['query'],
    ),
  'getUserAlbums' : IDL.Func(
      [IDL.Principal],
      [
        IDL.Record({
          'photoAlbums' : IDL.Vec(PhotoAlbumView),
          'videoAlbums' : IDL.Vec(VideoAlbumView),
        }),
      ],
      ['query'],
    ),
  'getUserChallengeCompletions' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(ChallengeCompletion)],
      ['query'],
    ),
  'getUserPhotoAlbums' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(PhotoAlbumView)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserStatusUpdates' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(StatusUpdate)],
      ['query'],
    ),
  'getUserVideoAlbums' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(VideoAlbumView)],
      ['query'],
    ),
  'healthcheckWithPhotos' : IDL.Func(
      [],
      [IDL.Record({ 'photoSystem' : IDL.Bool })],
      [],
    ),
  'healthcheckWithStorageCleanup' : IDL.Func(
      [],
      [
        IDL.Record({
          'storageSystem' : IDL.Bool,
          'operational' : IDL.Bool,
          'message' : IDL.Text,
        }),
      ],
      [],
    ),
  'initializeAccessControl' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'removeFromMemoryJar' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'removeMusicAttachment' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendLoveNote' : IDL.Func(
      [IDL.Text, IDL.Principal, IDL.Text],
      [IDL.Text],
      [],
    ),
  'setDailyChallenge' : IDL.Func(
      [IDL.Text, IDL.Text, PostCategory, Time],
      [DailyChallenge],
      [],
    ),
  'storeKindnessMatches' : IDL.Func(
      [IDL.Principal, IDL.Vec(KindnessMatch)],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const MusicAttachment = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'audioFile' : ExternalBlob,
    'artist' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const ChallengeCompletion = IDL.Record({
    'id' : IDL.Text,
    'user' : IDL.Principal,
    'challengeId' : IDL.Text,
    'timestamp' : Time,
    'postId' : IDL.Text,
  });
  const PostCategory = IDL.Variant({
    'other' : IDL.Null,
    'actsOfKindness' : IDL.Null,
    'environmental' : IDL.Null,
    'communityService' : IDL.Null,
  });
  const Post = IDL.Record({
    'id' : IDL.Text,
    'parentPostId' : IDL.Opt(IDL.Text),
    'video' : IDL.Opt(ExternalBlob),
    'author' : IDL.Principal,
    'likes' : IDL.Nat,
    'timestamp' : Time,
    'caption' : IDL.Text,
    'category' : PostCategory,
    'comments' : IDL.Nat,
    'photo' : IDL.Opt(ExternalBlob),
    'isFlagged' : IDL.Bool,
  });
  const UserProfile = IDL.Record({
    'bio' : IDL.Text,
    'principal' : IDL.Principal,
    'statusImage' : IDL.Opt(ExternalBlob),
    'name' : IDL.Text,
    'layoutPreferences' : IDL.Opt(IDL.Text),
    'statusText' : IDL.Opt(IDL.Text),
    'followers' : IDL.Nat,
    'following' : IDL.Nat,
    'profilePicture' : IDL.Opt(ExternalBlob),
  });
  const StatusUpdate = IDL.Record({
    'music' : IDL.Opt(MusicAttachment),
    'text' : IDL.Opt(IDL.Text),
    'timestamp' : Time,
    'image' : IDL.Opt(ExternalBlob),
  });
  const LoveNote = IDL.Record({
    'id' : IDL.Text,
    'recipient' : IDL.Principal,
    'sender' : IDL.Principal,
    'message' : IDL.Text,
    'timestamp' : Time,
  });
  const MemoryJarEntry = IDL.Record({ 'savedAt' : Time, 'postId' : IDL.Text });
  const PhotoAlbumView = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'photos' : IDL.Vec(ExternalBlob),
  });
  const VideoAlbumView = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'videos' : IDL.Vec(ExternalBlob),
  });
  const DailyChallenge = IDL.Record({
    'id' : IDL.Text,
    'date' : Time,
    'category' : PostCategory,
    'prompt' : IDL.Text,
  });
  const KindnessMatch = IDL.Record({
    'sharedCategories' : IDL.Vec(PostCategory),
    'withUser' : IDL.Principal,
    'compatibilityScore' : IDL.Nat,
    'reason' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addPhotoToAlbum' : IDL.Func([IDL.Text, ExternalBlob], [IDL.Bool], []),
    'addStatusUpdate' : IDL.Func(
        [IDL.Opt(IDL.Text), IDL.Opt(ExternalBlob), IDL.Opt(MusicAttachment)],
        [],
        [],
      ),
    'addToMemoryJar' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'addVideoToAlbum' : IDL.Func([IDL.Text, ExternalBlob], [IDL.Bool], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'attachMusicToStatus' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, ExternalBlob],
        [],
        [],
      ),
    'completeDailyChallenge' : IDL.Func(
        [IDL.Text, IDL.Text],
        [ChallengeCompletion],
        [],
      ),
    'createPhotoAlbum' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'createPost' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Opt(ExternalBlob),
          IDL.Opt(ExternalBlob),
          PostCategory,
        ],
        [Post],
        [],
      ),
    'createVideoAlbum' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'getAllMusicAttachments' : IDL.Func(
        [],
        [IDL.Vec(MusicAttachment)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getChallengeCompletions' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ChallengeCompletion)],
        ['query'],
      ),
    'getFriendsStatusUpdates' : IDL.Func(
        [IDL.Vec(IDL.Principal)],
        [IDL.Vec(StatusUpdate)],
        ['query'],
      ),
    'getLoveNotesCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getMusicAttachment' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(MusicAttachment)],
        ['query'],
      ),
    'getMyLoveNotes' : IDL.Func([], [IDL.Vec(LoveNote)], ['query']),
    'getMyMemoryJar' : IDL.Func([], [IDL.Vec(MemoryJarEntry)], ['query']),
    'getMyPhotoAlbums' : IDL.Func([], [IDL.Vec(PhotoAlbumView)], ['query']),
    'getMyVideoAlbums' : IDL.Func([], [IDL.Vec(VideoAlbumView)], ['query']),
    'getRippleChain' : IDL.Func([IDL.Text], [IDL.Vec(Post)], ['query']),
    'getTodaysChallenge' : IDL.Func([], [IDL.Opt(DailyChallenge)], ['query']),
    'getTopMatches' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(KindnessMatch)],
        ['query'],
      ),
    'getUserAlbums' : IDL.Func(
        [IDL.Principal],
        [
          IDL.Record({
            'photoAlbums' : IDL.Vec(PhotoAlbumView),
            'videoAlbums' : IDL.Vec(VideoAlbumView),
          }),
        ],
        ['query'],
      ),
    'getUserChallengeCompletions' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(ChallengeCompletion)],
        ['query'],
      ),
    'getUserPhotoAlbums' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(PhotoAlbumView)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserStatusUpdates' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(StatusUpdate)],
        ['query'],
      ),
    'getUserVideoAlbums' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(VideoAlbumView)],
        ['query'],
      ),
    'healthcheckWithPhotos' : IDL.Func(
        [],
        [IDL.Record({ 'photoSystem' : IDL.Bool })],
        [],
      ),
    'healthcheckWithStorageCleanup' : IDL.Func(
        [],
        [
          IDL.Record({
            'storageSystem' : IDL.Bool,
            'operational' : IDL.Bool,
            'message' : IDL.Text,
          }),
        ],
        [],
      ),
    'initializeAccessControl' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'removeFromMemoryJar' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'removeMusicAttachment' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendLoveNote' : IDL.Func(
        [IDL.Text, IDL.Principal, IDL.Text],
        [IDL.Text],
        [],
      ),
    'setDailyChallenge' : IDL.Func(
        [IDL.Text, IDL.Text, PostCategory, Time],
        [DailyChallenge],
        [],
      ),
    'storeKindnessMatches' : IDL.Func(
        [IDL.Principal, IDL.Vec(KindnessMatch)],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };