/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ExternalBlob = Uint8Array;
export interface MusicAttachment {
  'id' : string,
  'title' : string,
  'audioFile' : ExternalBlob,
  'artist' : string,
}
export interface PhotoAlbumView {
  'id' : string,
  'name' : string,
  'photos' : Array<ExternalBlob>,
}
export interface StatusUpdate {
  'music' : [] | [MusicAttachment],
  'text' : [] | [string],
  'timestamp' : Time,
  'image' : [] | [ExternalBlob],
}
export type Time = bigint;
export interface UserProfile {
  'bio' : string,
  'principal' : Principal,
  'statusImage' : [] | [ExternalBlob],
  'name' : string,
  'layoutPreferences' : [] | [string],
  'statusText' : [] | [string],
  'followers' : bigint,
  'following' : bigint,
  'profilePicture' : [] | [ExternalBlob],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface VideoAlbumView {
  'id' : string,
  'name' : string,
  'videos' : Array<ExternalBlob>,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addPhotoToAlbum' : ActorMethod<[string, ExternalBlob], boolean>,
  'addStatusUpdate' : ActorMethod<
    [[] | [string], [] | [ExternalBlob], [] | [MusicAttachment]],
    undefined
  >,
  'addVideoToAlbum' : ActorMethod<[string, ExternalBlob], boolean>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'attachMusicToStatus' : ActorMethod<
    [string, string, string, ExternalBlob],
    undefined
  >,
  'createPhotoAlbum' : ActorMethod<[string, string], undefined>,
  'createVideoAlbum' : ActorMethod<[string, string], undefined>,
  'getAllMusicAttachments' : ActorMethod<[], Array<MusicAttachment>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFriendsStatusUpdates' : ActorMethod<
    [Array<Principal>],
    Array<StatusUpdate>
  >,
  'getMusicAttachment' : ActorMethod<[string], [] | [MusicAttachment]>,
  'getMyPhotoAlbums' : ActorMethod<[], Array<PhotoAlbumView>>,
  'getMyVideoAlbums' : ActorMethod<[], Array<VideoAlbumView>>,
  'getUserAlbums' : ActorMethod<
    [Principal],
    {
      'photoAlbums' : Array<PhotoAlbumView>,
      'videoAlbums' : Array<VideoAlbumView>,
    }
  >,
  'getUserPhotoAlbums' : ActorMethod<[Principal], Array<PhotoAlbumView>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserStatusUpdates' : ActorMethod<[Principal], Array<StatusUpdate>>,
  'getUserVideoAlbums' : ActorMethod<[Principal], Array<VideoAlbumView>>,
  'healthcheckWithPhotos' : ActorMethod<[], { 'photoSystem' : boolean }>,
  'healthcheckWithStorageCleanup' : ActorMethod<
    [],
    { 'storageSystem' : boolean, 'operational' : boolean, 'message' : string }
  >,
  'initializeAccessControl' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'removeMusicAttachment' : ActorMethod<[string], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];