/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const MusicAttachment = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'audioFile' : ExternalBlob,
  'artist' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'bio' : IDL.Text,
  'principal' : IDL.Principal,
  'statusImage' : IDL.Opt(ExternalBlob),
  'name' : IDL.Text,
  'layoutPreferences' : IDL.Opt(IDL.Text),
  'statusText' : IDL.Opt(IDL.Text),
  'followers' : IDL.Nat,
  'following' : IDL.Nat,
  'profilePicture' : IDL.Opt(ExternalBlob),
});
export const Time = IDL.Int;
export const StatusUpdate = IDL.Record({
  'music' : IDL.Opt(MusicAttachment),
  'text' : IDL.Opt(IDL.Text),
  'timestamp' : Time,
  'image' : IDL.Opt(ExternalBlob),
});
export const PhotoAlbumView = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'photos' : IDL.Vec(ExternalBlob),
});
export const VideoAlbumView = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'videos' : IDL.Vec(ExternalBlob),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addPhotoToAlbum' : IDL.Func([IDL.Text, ExternalBlob], [IDL.Bool], []),
  'addStatusUpdate' : IDL.Func(
      [IDL.Opt(IDL.Text), IDL.Opt(ExternalBlob), IDL.Opt(MusicAttachment)],
      [],
      [],
    ),
  'addVideoToAlbum' : IDL.Func([IDL.Text, ExternalBlob], [IDL.Bool], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'attachMusicToStatus' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, ExternalBlob],
      [],
      [],
    ),
  'createPhotoAlbum' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'createVideoAlbum' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'getAllMusicAttachments' : IDL.Func(
      [],
      [IDL.Vec(MusicAttachment)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFriendsStatusUpdates' : IDL.Func(
      [IDL.Vec(IDL.Principal)],
      [IDL.Vec(StatusUpdate)],
      ['query'],
    ),
  'getMusicAttachment' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(MusicAttachment)],
      ['query'],
    ),
  'getMyPhotoAlbums' : IDL.Func([], [IDL.Vec(PhotoAlbumView)], ['query']),
  'getMyVideoAlbums' : IDL.Func([], [IDL.Vec(VideoAlbumView)], ['query']),
  'getUserAlbums' : IDL.Func(
      [IDL.Principal],
      [
        IDL.Record({
          'photoAlbums' : IDL.Vec(PhotoAlbumView),
          'videoAlbums' : IDL.Vec(VideoAlbumView),
        }),
      ],
      ['query'],
    ),
  'getUserPhotoAlbums' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(PhotoAlbumView)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserStatusUpdates' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(StatusUpdate)],
      ['query'],
    ),
  'getUserVideoAlbums' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(VideoAlbumView)],
      ['query'],
    ),
  'healthcheckWithPhotos' : IDL.Func(
      [],
      [IDL.Record({ 'photoSystem' : IDL.Bool })],
      [],
    ),
  'healthcheckWithStorageCleanup' : IDL.Func(
      [],
      [
        IDL.Record({
          'storageSystem' : IDL.Bool,
          'operational' : IDL.Bool,
          'message' : IDL.Text,
        }),
      ],
      [],
    ),
  'initializeAccessControl' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'removeMusicAttachment' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const MusicAttachment = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'audioFile' : ExternalBlob,
    'artist' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'bio' : IDL.Text,
    'principal' : IDL.Principal,
    'statusImage' : IDL.Opt(ExternalBlob),
    'name' : IDL.Text,
    'layoutPreferences' : IDL.Opt(IDL.Text),
    'statusText' : IDL.Opt(IDL.Text),
    'followers' : IDL.Nat,
    'following' : IDL.Nat,
    'profilePicture' : IDL.Opt(ExternalBlob),
  });
  const Time = IDL.Int;
  const StatusUpdate = IDL.Record({
    'music' : IDL.Opt(MusicAttachment),
    'text' : IDL.Opt(IDL.Text),
    'timestamp' : Time,
    'image' : IDL.Opt(ExternalBlob),
  });
  const PhotoAlbumView = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'photos' : IDL.Vec(ExternalBlob),
  });
  const VideoAlbumView = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'videos' : IDL.Vec(ExternalBlob),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addPhotoToAlbum' : IDL.Func([IDL.Text, ExternalBlob], [IDL.Bool], []),
    'addStatusUpdate' : IDL.Func(
        [IDL.Opt(IDL.Text), IDL.Opt(ExternalBlob), IDL.Opt(MusicAttachment)],
        [],
        [],
      ),
    'addVideoToAlbum' : IDL.Func([IDL.Text, ExternalBlob], [IDL.Bool], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'attachMusicToStatus' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, ExternalBlob],
        [],
        [],
      ),
    'createPhotoAlbum' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'createVideoAlbum' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'getAllMusicAttachments' : IDL.Func(
        [],
        [IDL.Vec(MusicAttachment)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFriendsStatusUpdates' : IDL.Func(
        [IDL.Vec(IDL.Principal)],
        [IDL.Vec(StatusUpdate)],
        ['query'],
      ),
    'getMusicAttachment' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(MusicAttachment)],
        ['query'],
      ),
    'getMyPhotoAlbums' : IDL.Func([], [IDL.Vec(PhotoAlbumView)], ['query']),
    'getMyVideoAlbums' : IDL.Func([], [IDL.Vec(VideoAlbumView)], ['query']),
    'getUserAlbums' : IDL.Func(
        [IDL.Principal],
        [
          IDL.Record({
            'photoAlbums' : IDL.Vec(PhotoAlbumView),
            'videoAlbums' : IDL.Vec(VideoAlbumView),
          }),
        ],
        ['query'],
      ),
    'getUserPhotoAlbums' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(PhotoAlbumView)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserStatusUpdates' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(StatusUpdate)],
        ['query'],
      ),
    'getUserVideoAlbums' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(VideoAlbumView)],
        ['query'],
      ),
    'healthcheckWithPhotos' : IDL.Func(
        [],
        [IDL.Record({ 'photoSystem' : IDL.Bool })],
        [],
      ),
    'healthcheckWithStorageCleanup' : IDL.Func(
        [],
        [
          IDL.Record({
            'storageSystem' : IDL.Bool,
            'operational' : IDL.Bool,
            'message' : IDL.Text,
          }),
        ],
        [],
      ),
    'initializeAccessControl' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'removeMusicAttachment' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };